# Generated by Django 4.2 on 2025-11-25 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('nombres', models.CharField(db_column='Nombres', max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(db_column='Apellidos', max_length=100, verbose_name='Apellidos')),
                ('telefono', models.CharField(db_column='Telefono', max_length=20, verbose_name='Teléfono')),
                ('direccion', models.CharField(db_column='Direccion', max_length=255, verbose_name='Dirección')),
                ('correo', models.EmailField(db_column='Correo', max_length=100, verbose_name='Correo Electrónico')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_column='FechaRegistro', verbose_name='Fecha de Registro')),
                ('estado', models.BooleanField(db_column='Estado', default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'Cliente',
            },
        ),
    ]
