# Generated by Django 4.2 on 2025-11-25 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100, verbose_name='Nombre')),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=255, verbose_name='Descripción')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_column='FechaRegistro', verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'Departamento',
            },
        ),
    ]
