# Generated by Django 4.2 on 2025-11-25 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marca', '0001_initial'),
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100, verbose_name='Nombre del Producto')),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=255, verbose_name='Descripción')),
                ('precio_unitario', models.DecimalField(db_column='PrecioUnitario', decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('stock_actual', models.IntegerField(db_column='StockActual', verbose_name='Stock Actual')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_column='FechaRegistro', verbose_name='Fecha de Registro')),
                ('estado', models.BooleanField(db_column='Estado', default=True, verbose_name='Activo')),
                ('marca', models.ForeignKey(db_column='MarcaId', on_delete=django.db.models.deletion.PROTECT, to='marca.marca', verbose_name='Marca')),
                ('proveedor', models.ForeignKey(db_column='ProveedorId', on_delete=django.db.models.deletion.PROTECT, to='proveedor.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'Producto',
            },
        ),
    ]
