# Generated by Django 4.2 on 2025-11-25 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('nombres', models.CharField(db_column='Nombres', max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(db_column='Apellidos', max_length=100, verbose_name='Apellidos')),
                ('cargo', models.CharField(db_column='Cargo', max_length=100, verbose_name='Cargo')),
                ('telefono', models.CharField(db_column='Telefono', max_length=20, verbose_name='Teléfono')),
                ('correo', models.EmailField(db_column='Correo', max_length=100, verbose_name='Correo Electrónico')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_column='FechaRegistro', verbose_name='Fecha de Registro')),
                ('estado', models.BooleanField(db_column='Estado', default=True, verbose_name='Activo')),
                ('departamento', models.ForeignKey(db_column='DepartamentoId', on_delete=django.db.models.deletion.PROTECT, to='departamento.departamento', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'Empleado',
            },
        ),
    ]
