# Generated by Django 4.2 on 2025-11-28 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleado', '0001_initial'),
        ('producto', '0001_initial'),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_column='Fecha')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_column='FechaRegistro')),
                ('cliente', models.ForeignKey(db_column='ClienteId', on_delete=django.db.models.deletion.PROTECT, to='cliente.cliente')),
                ('empleado', models.ForeignKey(db_column='EmpleadoId', on_delete=django.db.models.deletion.PROTECT, to='empleado.empleado')),
            ],
            options={
                'db_table': 'Venta',
            },
        ),
        migrations.CreateModel(
            name='FacturaVenta',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True, db_column='FechaEmision')),
                ('total', models.DecimalField(db_column='Total', decimal_places=2, max_digits=12)),
                ('iva', models.DecimalField(db_column='IVA', decimal_places=2, max_digits=12)),
                ('total_con_iva', models.DecimalField(db_column='TotalConIVA', decimal_places=2, max_digits=12)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_column='FechaRegistro')),
                ('venta', models.ForeignKey(db_column='VentaId', on_delete=django.db.models.deletion.CASCADE, to='venta.venta')),
            ],
            options={
                'db_table': 'FacturaVenta',
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(db_column='Cantidad')),
                ('precio_unitario', models.DecimalField(db_column='PrecioUnitario', decimal_places=2, max_digits=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_column='FechaRegistro')),
                ('producto', models.ForeignKey(db_column='ProductoId', on_delete=django.db.models.deletion.PROTECT, to='producto.producto')),
                ('venta', models.ForeignKey(db_column='VentaId', on_delete=django.db.models.deletion.CASCADE, to='venta.venta')),
            ],
            options={
                'db_table': 'DetalleVenta',
            },
        ),
    ]
