# Generated by Django 4.2 on 2025-11-25 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100, verbose_name='Nombre Comercial')),
                ('telefono', models.CharField(db_column='Telefono', max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(db_column='Email', max_length=100, verbose_name='Correo Electrónico')),
                ('sitio_web', models.URLField(db_column='SitioWeb', max_length=150, verbose_name='Sitio Web')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_column='FechaRegistro', verbose_name='Fecha de Registro')),
                ('estado', models.BooleanField(db_column='Estado', default=True, verbose_name='Activo')),
                ('pais', models.ForeignKey(db_column='PaisId', on_delete=django.db.models.deletion.PROTECT, to='pais.pais', verbose_name='País')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'Proveedor',
            },
        ),
    ]
