# Generated by Django 4.2 on 2025-11-25 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100, verbose_name='Nombre de la Marca')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_column='FechaRegistro', verbose_name='Fecha de Registro')),
                ('proveedor', models.ForeignKey(db_column='ProveedorId', on_delete=django.db.models.deletion.PROTECT, to='proveedor.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'db_table': 'Marca',
            },
        ),
    ]
